### ISSUE TITLE
error after upload fresh library  

### ISSUE THREAD

**Issue by aqildad-create** [pschatzmann/arduino-audio-tools#955] opened 2023-08-04 07:21 UTC
every thing was working on previous version but after upload fresh library  getting below 

![image](https://github.com/pschatzmann/arduino-audio-tools/assets/65456998/818ee6b4-7a03-4db6-a563-ca4f73188c6b)

**Comment by pschatzmann** [comment] 2023-08-04 07:41
Please don't provide pictures but the proper stacktrace in text. 
W/o line numbers I can't really help!

**Comment by aqildad-create** [comment] 2023-08-04 07:45
All right but I don't have the text right now because I have delete the latest version and copying previous version for trouble shooting . 
But latest version have some channel conversing issues I guess.

**Comment by aqildad-create** [comment] 2023-08-04 07:49
I confirm now that old version is again working.

**Comment by pschatzmann** [comment] 2023-08-05 12:13
I am closing this issue since I can't reproduce it myself. 
I guess it might be related to [this correction](https://github.com/pschatzmann/arduino-audio-tools/commit/1a91735712700df53e954341ccc101f22b1f9240)...

Feel free to reopen it when you are able to provide the necessary information.

Or even better, if you see where it is crashing in your use case you can try to provide the correction yourself and share it

**Closed by pschatzmann** 2023-08-05 12:13 UTC
