### ISSUE TITLE
Audio tools have some weird bugs

### ISSUE THREAD

**Issue by G-Roman1988** [pschatzmann/arduino-audio-tools#1818] opened 2024-12-02 14:44 UTC
### Problem Description

Hello!.  first of all, I want to thank you for your work in such a library. I am getting such weird errors in terminal. Warning: Pin '13' not set up because of conflict 
[W] I2SESP32V1.h : 187 - Using channel_format: I2SChannelSelect::Left for mono .. but it works (plays sound). 
here is the code
 as I did: #include "esp_timer.h"
#include "AudioTools.h"
#include "AudioTools/AudioLibs/AudioBoardStream.h"
#include "beep.h" AudioInfo info(48000, 1, 16);
 //AnalogAudioStream out;
//AudioKitStream out;
//I2SStream out;
AudioBoardStream out(AudioKitEs8388V1);
MemoryStream music(Beep_array, BeepArray_len);
StreamCopy copier(out, music);

 void setup() {
Serial.begin(115200);
BLEDevice::init("punct de emiter");
personalserver();
personalBeacon();
  Serial.println("asteptam o conectare ...");
  //auto cfg = out.defaultConfig();
  //cfg.sample_rate = 48000;
  //cfg.channels = 1;

      auto config = out.defaultConfig(TX_MODE);
  config.copyFrom(info);  
//config.auto_clear = true;
//config.clear();
//config.use_apll = true;
out.begin(config);
}
 i changed AudioBoardStream out(AudioKitEs8388V1); to AudioBoardStream out(AudioKitEs8388V2); I have several errors and no sound. when I used I2SStream out; it was just this error [W] I2SESP32V1.h : 187 - Using channel_format: I2SChannelSelect::Left for mono  but the sound is not heard. and when i updated to version arduino-audio-tools-1.0.1 I got the following error while compiling (loading)  AudioLibs/AudioBoardStream.h:4,
                 from E:\Documents\Arduino\vocespoint\vocespoint.ino:12:
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/I2SCodecStream.h:30:43: error: 'UNDEFINED' is not a member of 'audio_driver::PinFunction'
   30 |   PinFunction i2s_function = PinFunction::UNDEFINED; //CODEC;
      |                                           ^~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/I2SCodecStream.h: In member function 'void audio_tools::I2SCodecStream::setupI2SFunction()':
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/I2SCodecStream.h:236:42: error: 'UNDEFINED' is not a member of 'audio_driver::PinFunction'
  236 |     if (cfg.i2s_function == PinFunction::UNDEFINED){
      |                                          ^~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h: At global scope:
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:21:41: error: 'AudioDriverKey' has not been declared
   21 |     AudioBoardAction(AudioBoard &board, AudioDriverKey key) {
      |                                         ^~~~~~~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:25:5: error: 'AudioDriverKey' does not name a type; did you mean 'AudioWriter'?
   25 |     AudioDriverKey key;
      |     ^~~~~~~~~~~~~~
      |     AudioWriter
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:62:18: error: 'AudioDriverKey' has not been declared
   62 |   void addAction(AudioDriverKey key, void (*action)(bool, int, void *),
      |                  ^~~~~~~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:73:18: error: 'AudioDriverKey' has not been declared
   73 |   void addAction(AudioDriverKey key, void (*actionOn)(bool, int, void *),
      |                  ^~~~~~~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:92:8: error: 'void audio_tools::AudioBoardStream::addAction(int, void (*)(bool, int, void*), void*)' cannot be overloaded with 'void audio_tools::AudioBoardStream::addAction(int, void (*)(bool, int, void*), void*)'
   92 |   void addAction(int pin, void (*action)(bool, int, void *),
      |        ^~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:62:8: note: previous declaration 'void audio_tools::AudioBoardStream::addAction(int, void (*)(bool, int, void*), void*)'
   62 |   void addAction(AudioDriverKey key, void (*action)(bool, int, void *),
      |        ^~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h: In constructor 'audio_tools::AudioBoardStream::AudioBoardAction::AudioBoardAction(audio_driver::AudioBoard&, int)':
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:22:13: error: 'struct audio_tools::AudioBoardStream::AudioBoardAction' has no member named 'key'
   22 |       this->key = key;
      |             ^~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h: In member function 'virtual int audio_tools::AudioBoardStream::AudioBoardAction::id()':
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:27:32: error: 'key' was not declared in this scope; did you mean 'key_t'?
   27 |     int id() override { return key | 0x400; }
      |                                ^~~
      |                                key_t
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h: In member function 'virtual bool audio_tools::AudioBoardStream::AudioBoardAction::readValue()':
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:28:49: error: 'class audio_driver::AudioBoard' has no member named 'isKeyPressed'
   28 |     bool readValue() override { return p_board->isKeyPressed(key); }
      |                                                 ^~~~~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:28:62: error: 'key' was not declared in this scope; did you mean 'key_t'?
   28 |     bool readValue() override { return p_board->isKeyPressed(key); }
      |                                                              ^~~
      |                                                              key_t
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h: In member function 'bool audio_tools::AudioBoardStream::isKeyPressed(int)':
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:375:9: error: no match for 'operator!' (operand type is 'audio_driver::AudioBoard')
  375 |     if (!board()) return false;
      |         ^~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:375:9: note: candidate: 'operator!(bool)' (built-in)
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:375:9: note:   no known conversion for argument 1 from 'audio_driver::AudioBoard' to 'bool'
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:376:20: error: 'class audio_driver::AudioBoard' has no member named 'isKeyPressed'
  376 |     return board().isKeyPressed(key);
      |                    ^~~~~~~~~~~~

exit status 1

Compilation error: exit status 1
In file included from e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:4,
                 from E:\Documents\Arduino\vocespoint\vocespoint.ino:12:
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/I2SCodecStream.h:30:43: error: 'UNDEFINED' is not a member of 'audio_driver::PinFunction'
   30 |   PinFunction i2s_function = PinFunction::UNDEFINED; //CODEC;
      |                                           ^~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/I2SCodecStream.h: In member function 'void audio_tools::I2SCodecStream::setupI2SFunction()':
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/I2SCodecStream.h:236:42: error: 'UNDEFINED' is not a member of 'audio_driver::PinFunction'
  236 |     if (cfg.i2s_function == PinFunction::UNDEFINED){
      |                                          ^~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h: At global scope:
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:21:41: error: 'AudioDriverKey' has not been declared
   21 |     AudioBoardAction(AudioBoard &board, AudioDriverKey key) {
      |                                         ^~~~~~~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:25:5: error: 'AudioDriverKey' does not name a type; did you mean 'AudioWriter'?
   25 |     AudioDriverKey key;
      |     ^~~~~~~~~~~~~~
      |     AudioWriter
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:62:18: error: 'AudioDriverKey' has not been declared
   62 |   void addAction(AudioDriverKey key, void (*action)(bool, int, void *),
      |                  ^~~~~~~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:73:18: error: 'AudioDriverKey' has not been declared
   73 |   void addAction(AudioDriverKey key, void (*actionOn)(bool, int, void *),
      |                  ^~~~~~~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:92:8: error: 'void audio_tools::AudioBoardStream::addAction(int, void (*)(bool, int, void*), void*)' cannot be overloaded with 'void audio_tools::AudioBoardStream::addAction(int, void (*)(bool, int, void*), void*)'
   92 |   void addAction(int pin, void (*action)(bool, int, void *),
      |        ^~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:62:8: note: previous declaration 'void audio_tools::AudioBoardStream::addAction(int, void (*)(bool, int, void*), void*)'
   62 |   void addAction(AudioDriverKey key, void (*action)(bool, int, void *),
      |        ^~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h: In constructor 'audio_tools::AudioBoardStream::AudioBoardAction::AudioBoardAction(audio_driver::AudioBoard&, int)':
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:22:13: error: 'struct audio_tools::AudioBoardStream::AudioBoardAction' has no member named 'key'
   22 |       this->key = key;
      |             ^~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h: In member function 'virtual int audio_tools::AudioBoardStream::AudioBoardAction::id()':
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:27:32: error: 'key' was not declared in this scope; did you mean 'key_t'?
   27 |     int id() override { return key | 0x400; }
      |                                ^~~
      |                                key_t
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h: In member function 'virtual bool audio_tools::AudioBoardStream::AudioBoardAction::readValue()':
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:28:49: error: 'class audio_driver::AudioBoard' has no member named 'isKeyPressed'
   28 |     bool readValue() override { return p_board->isKeyPressed(key); }
      |                                                 ^~~~~~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:28:62: error: 'key' was not declared in this scope; did you mean 'key_t'?
   28 |     bool readValue() override { return p_board->isKeyPressed(key); }
      |                                                              ^~~
      |                                                              key_t
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h: In member function 'bool audio_tools::AudioBoardStream::isKeyPressed(int)':
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:375:9: error: no match for 'operator!' (operand type is 'audio_driver::AudioBoard')
  375 |     if (!board()) return false;
      |         ^~~~~~~~
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:375:9: note: candidate: 'operator!(bool)' (built-in)
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:375:9: note:   no known conversion for argument 1 from 'audio_driver::AudioBoard' to 'bool'
e:\Documents\Arduino\libraries\audio-tools\src/AudioTools/AudioLibs/AudioBoardStream.h:376:20: error: 'class audio_driver::AudioBoard' has no member named 'isKeyPressed'
  376 |     return board().isKeyPressed(key);
      |                    ^~~~~~~~~~~~

exit status 1

Compilation error: exit status 1  .. the same error even with an example from the library when the version is arduino-audio-tools-1.0.1 but with version 1.0.0 it gives me the errors in the terminal that I said above. where are they not doing it right or is it a compatibility issue.

### Device Description

esp32 dev module

### Sketch

```cpp
#include <BLEDescriptor.h>
#include<BLECharacteristic.h>
#include<BLE2902.h>
#include<BLEAdvertisedDevice.h>
#include<BLEDevice.h>
#include<BLEUtils.h>
#include<BLEBeacon.h>
#include<BLEUUID.h>
#include<BLEServer.h>
#include "esp_timer.h"
#include "AudioTools.h"
#include "AudioTools/AudioLibs/AudioBoardStream.h"
#include "beep.h"
//using namespace audio_tools;
AudioInfo info(48000, 1, 16);
void sunet();
void chemare();
void stopchemare();
void trimitereMesaj(String mesajNotify);
//AnalogAudioStream out;
//AudioKitStream out;
//I2SStream out;
AudioBoardStream out(AudioKitEs8388V1);
MemoryStream music(Beep_array, BeepArray_len);
StreamCopy copier(out, music);

BLEAdvertising *pAdvertising;
BLEServer *pServer = NULL;
BLECharacteristic * pTxCharacteristic;
bool deviceConnected = false;
bool oldDeviceConnected = false;
bool notificare = false;
bool StatusBeep =false;
String mesagiValue = "salut";
int perioada = 10, contor =0;
#define BUUID "A134D0B2-1DA2-1BA7-C94C-E8E00C9F7A2D"
#define SERVICE_UUID           "6E400001-B5A3-F393-E0A9-E50E24DCCA9E" // UART service UUID
#define CHARACTERISTIC_UUID_RX "6E400002-B5A3-F393-E0A9-E50E24DCCA9E"
#define CHARACTERISTIC_UUID_TX "6E400003-B5A3-F393-E0A9-E50E24DCCA9E"

esp_timer_handle_t timer;
hw_timer_t *My_timer = NULL;
//void IRAM_ATTR onTimer(){
void onTimer(void* arg){
  sunet();
  contor++;
  Serial.print("a trecut o secunda");
}

class MyServerCallbacks: public BLEServerCallbacks {
    void onConnect(BLEServer* pServer) {
      deviceConnected = true;
      trimitereMesaj("ion dominiuc alexei mateievici");
      Serial.print("este o conectare noua");
      };
        
    void onDisconnect(BLEServer* pServer) {
      deviceConnected = false;
Serial.print("clientul sa deconectat");      
pServer->startAdvertising();
        Serial.println("start advertising");
        if (StatusBeep)
        stopchemare();
        }
};

class MyCallbacks: public BLECharacteristicCallbacks {
    void onWrite(BLECharacteristic *pCharacteristic) {
      //std::string rxValue = pCharacteristic->getValue();
      String rxValue = pCharacteristic->getValue();
Serial.print(rxValue.c_str());

if (rxValue == "1") {
chemare();
trimitereMesaj("Se redă semnalu sonor");
}
if(rxValue == "0") {
stopchemare();
Serial.println("sa livrat 0");
}
    }
};

class MyDescriptorCallbacks: public BLEDescriptorCallbacks {
  void onWrite(BLEDescriptor* pDescriptor){
uint16_t descriptorValue = pDescriptor ->getValue()[0]|(pDescriptor ->getValue()[1] << 8);
Serial.println(descriptorValue);
if (descriptorValue == 1) {
//pTxCharacteristic ->setNotifyProperty(true);

} else if (descriptorValue == 0) {
//pTxCharacteristic ->setNotifyProperty(false);
//pDescriptor -> setValue(descriptorValue);
}
  };
  void onRead(BLEDescriptor* pDescriptor){
pDescriptor -> getValue();
}
};

void personalserver(){
  pServer = BLEDevice::createServer();
  pServer->setCallbacks(new MyServerCallbacks());
BLEService *pService = pServer->createService(SERVICE_UUID);
  pTxCharacteristic = pService->createCharacteristic(CHARACTERISTIC_UUID_TX, BLECharacteristic::PROPERTY_NOTIFY);
  BLEDescriptor *pBleDescriptor = new BLE2902();
  pBleDescriptor -> setCallbacks(new MyDescriptorCallbacks());
                        pTxCharacteristic->addDescriptor(pBleDescriptor);
pTxCharacteristic->setNotifyProperty(true);
BLECharacteristic * pRx = pService->createCharacteristic(CHARACTERISTIC_UUID_RX, BLECharacteristic::PROPERTY_WRITE);
pRx->setCallbacks(new MyCallbacks());
pRx->setWriteProperty(true);
  pService->start();
//pAdvertising = pServer->getAdvertising();  
//pAdvertising->start();
}

void personalBeacon()
{
pAdvertising = pServer->getAdvertising();
    BLEBeacon myBeacon;
  myBeacon.setManufacturerId(0x004c);
  myBeacon.setMajor(1);
  myBeacon.setMinor(24);
  myBeacon.setSignalPower(0xc5);
  BLEUUID bleUUID = BLEUUID(BUUID);
bleUUID = bleUUID.to128();
  myBeacon.setProximityUUID(BLEUUID(bleUUID.getNative()->uuid.uuid128, 16, true));
  BLEAdvertisementData advertisementData;
  advertisementData.setFlags(0x1A);
  advertisementData.setManufacturerData(myBeacon.getData());
  pAdvertising->setAdvertisementData(advertisementData);
//  pAdvertising->setAdvertisementType(ADV_TYPE_IND);

    pAdvertising->start();
}
void setup() {
Serial.begin(115200);
BLEDevice::init("punct de emiter");
personalserver();
personalBeacon();
  Serial.println("asteptam o conectare ...");
  //auto cfg = out.defaultConfig();
  //cfg.sample_rate = 48000;
  //cfg.channels = 1;

      auto config = out.defaultConfig(TX_MODE);
  config.copyFrom(info);  
//config.auto_clear = true;
//config.clear();
//config.use_apll = true;
out.begin(config);
}
void chemare(){
  if (timer == NULL) {
      // Configurăm structura timer-ului
const esp_timer_create_args_t timer_args = {
  .callback = &onTimer, .arg = NULL, .dispatch_method = ESP_TIMER_TASK, .name ="soundTimer"
};
    // Creăm timer-ul
esp_timer_create(&timer_args, &timer);
Serial.print("timer-ul este creat, pornim timer-ul");
// Pornim timer-ul să se declanșeze periodic la fiecare 1 secundă 
esp_timer_start_periodic(timer, 1000000);
  }
  sunet();
  StatusBeep = true;
  //My_timer = timerBegin(1000000);
//timerStart(My_timer);
  }
void stopchemare(){
  StatusBeep = false;
  if (timer != NULL) {
    Serial.print("oprim timer-ul");
    //Oprire timer și eliberare resurse
  esp_timer_stop(timer);
esp_timer_delete(timer);
// Resetăm pointer-ul timer-ului
timer = NULL;
  }
  //timerStop(My_timer);
  //timerEnd(My_timer);
  contor = 0;
}
void sunet(){
    music.begin();
do {
  if (music.begin())
        copier.copy();
}while (!copier.copy());
if (!copier.copy());
music.end();
}
void trimitereMesaj(String mesajNotify){
  mesagiValue =mesajNotify;
  pTxCharacteristic->setValue(mesajNotify.c_str());
pTxCharacteristic->notify();
//mesajNotify ++;
}

void loop() {
          
    if (contor >= perioada)
  stopchemare();
  //Serial.print("perioada de 10 secunde a expirat");
}
```

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment] 2024-12-02 15:29
When you post some code please use the proper [code formatting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). and if you do so, please post a minimal sketch which highlights the problem that can be reproduced by somebody else then you!

Please don't raise an issue for your user errors: The documentation is giving the information when to use AudioBoardStream and it is definitly not for a esp32 dev module!

And finally I also have no idea which development tools and which ESP32 core version you are using.
I am closing this issue, because with the current information I can't help you!

**Closed by pschatzmann** 2024-12-02 15:29 UTC
