### ISSUE TITLE
Don't read files from sd card, because of missing '/' in file path

### ISSUE THREAD

**Issue by Sergionn** [pschatzmann/arduino-audio-tools#378] opened 2022-09-27 09:00 UTC
Don't read files from sd card, because of missing '/' in file path

**Comment by pschatzmann** [comment] 2022-09-27 09:05
I am afraid that you need to provide more details:
- what example
- for which SD library

**Comment by luke2023** [comment] 2022-09-27 09:33
> Don't read files from sd card, because of missing '/' in file path

You mean the issue #290

**Comment by pschatzmann** [comment] 2022-09-27 09:35
No: https://github.com/pschatzmann/arduino-audio-tools/issues/373

**Comment by pschatzmann** [comment] 2022-10-04 06:14
I am closing this issue because I did not get the requested information and I can't reproduce the issue myself

**Closed by pschatzmann** 2022-10-04 06:14 UTC
